server:
  port: 8081
  servlet:
    context-path: /profile
eureka:
  instance:
    prefer-ip-address: true   # Sử dụng IP thay vì hostname
    ip-address: 127.0.0.1  # Cố định IP thành localhost
    hostname: localhost  # Đảm bảo Eureka sử dụng localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  boot:
    message: Hello Profile Service, Spring Cloud Bus
